# Generated by Django 4.0.2 on 2022-02-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
    ]
